@extends('layouts.noheader')
@section('content')
    @include('partials.ajax-frontpage-link')
    @include('partials.search')
    @include('partials.hero')
    @include('partials.promocards')
    @include('partials.destinations')
    @include('partials.submit-new-invite')
@endsection